### ISSUE TITLE
Can't load this repo

### ISSUE THREAD

**Issue by MincePie** [nass59/turborepo-nextjs#2]
Hi @nass59 

I can't load your repo.

Errors are:

docs:dev: error - Failed to load next.config.js, see more info here https://nextjs.org/docs/messages/next-config-error
docs:dev: Error: next-transpile-modules - an unexpected error happened when trying to resolve "ui". Are you sure the name of the module you are trying to transpile is correct, and it has a package.json with a "main" or an "exports" field?

Error: Can't resolve 'ui/package.json' in '//turborepo-nextjs/apps/docs'
docs:dev:     at getPackageRootDirectory (//turborepo-nextjs/node_modules/next-transpile-modules/src/next-transpile-modules.js:118:15)
docs:dev:     at Array.map (<anonymous>)
docs:dev:     at withTM (| Header |

| Cell | /turborepo-nextjs/node_modules/next-transpile-modules/src/next-transpile-modules.js:127:34)
docs:dev:     at Object.<anonymous> (| Header |

| Cell | /turborepo-nextjs/apps/docs/next.config.js:3:18)
docs:dev:     at Module._compile (node:internal/modules/cjs/loader:1275:14)
docs:dev:     at Module._extensions..js (node:internal/modules/cjs/loader:1329:10)
docs:dev:     at Module.load (node:internal/modules/cjs/loader:1133:32)
docs:dev:     at Module._load (node:internal/modules/cjs/loader:972:12)
docs:dev:     at ModuleWrap.<anonymous> (node:internal/modules/esm/translators:168:29)
docs:dev:     at ModuleJob.run (node:internal/modules/esm/module_job:193:25)
docs:dev:  ELIFECYCLE  Command failed with exit code 1.
docs:dev: ERROR: command finished with error: command (| Header |
|--------|
| Cell | /turborepo-nextjs/apps/docs) pnpm run dev exited (1)

Do you have a working version of what you released?

thank you

**Comment by nass59** [comment]
Hello @MincePie yes sorry it's fixed, I changed many things and now the docs folder has been deleted and the ui package has been renamed also.
Thanks for this issue :)
